import commands.animate_cli as a_cli
import commands.send_wrapper as sw

frames = str(
    
    '(ヘ°-°)ヘ ┬─┬ \xa0'
    '\n#!\n'
    '(ヘ°-°)ヘ ┬─┬ \xa0'
    '\n#!\n'
    '(ヘ°□°)ヘ ┬─┬ \xa0'
    '\n#!\n'
    '(ヘ°□°)ヘ ┬─┬ \xa0'
    '\n#!\n'
    '(ヘ°-°)ヘ ┬─┬ \xa0'
    '\n#!\n'
    '(ヘ°-°)ヘ ┬─┬ \xa0'
    '\n#!\n'
    '(ヘ‵□′)ヘ ┬─┬ \xa0'
    '\n#!\n'
    '(ヘ‵□′)ヘ ┬─┬ \xa0'
    '\n#!\n'
    '(╯‵□′）╯\xa0︵ ┻━┻' 
    '\n#!\n'
    '╯‵□′）╯\xa0－－┻━┻'
    '\n#!\n'
    '‵□′）╯－－－┻━┻'
    '\n#!\n'
    '-°）╯－－－－┻━┻'
    '\n#!\n'
    '°）╯－－－－┻━┻'
    '\n#!\n'
    '）╯－－－－┻━┻'
    '\n#!\n'
    '╯－－－－┻━┻'
    '\n#!\n'
    '－－－－┻━┻'
    '\n#!\n'
    '－－－┻━┻ \xa0 \xa0˦'
    '\n#!\n'
    '－－┻━┻ \xa0 \xa0˦\xa0'
    '\n#!\n'
    '\xa0\xa0\xa0－┻━┻ \xa0\xa0 ˦ \xa0'
    '\n#!\n'
    '\xa0\xa0\xa0\xa0－┻━┻ \xa0 ˦ \xa0'
    '\n#!\n'
    '\xa0\xa0\xa0\xa0\xa0\xa0 ┻━┻ ˦ \xa0'
    '\n#!\n'
    '\xa0\xa0\xa0\xa0\xa0 ┻ ━┻ ˦ \xa0'
    '\n#!\n'
    '\xa0\xa0\xa0\xa0\xa0 ┻ ━┻ ˦ \xa0'
    '\n#!\n'
    '\xa0\xa0\xa0\xa0\xa0 ┻ ━┻ ˦ \xa0'
    '\n#!\n'
    '）\xa0\xa0\xa0\xa0 ┻ ━┻ ˦ \xa0'
    '\n#!\n'
    'ಥ）\xa0\xa0\xa0 ┻ ━┻ ˦'
    '\n#!\n'
    '-ಥ）\xa0\xa0 ┻ ━┻ ˦'
    '\n#!\n'
    'ಥ-ಥ）\xa0 ┻ ━┻ ˦ '
    '\n#!\n'
    '(ಥ-ಥ） ┻ ━┻ '
    '\n#!\n'
    '(ಥ-ಥ） ┻ ━┻ '
    '\n#!\n'
    '(ಥ-ಥ） ┻ ━┻ '
    '\n#!\n'

)

async def run(message):
    await a_cli.animate(message,frames,250,1)
    await sw.wrapperSend(message, "Table flip animation completed!")
    return